name: Structure
description: Mindful screentime and project management.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  provider: ^6.0.1
  build_runner: ^2.4.13
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  icons_plus: ^5.0.0
  flutter_markdown: ^0.7.4+3
  toml: ^0.16.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  flutter_html: ^3.0.0-beta.2
  flutter_highlight: ^0.7.0
  markdown: ^7.1.1
  window_manager: ^0.4.3
  flutter_code_editor: ^0.3.2
  dropdown_search: ^6.0.1
  webview_flutter: ^4.10.0
  webview_windows: ^0.4.0
  flutter_gen: ^5.8.0
  visibility_detector: ^0.4.0+2
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1

dev_dependencies:
  objectbox_generator: ^4.0.3
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: 3.0.2
  flutter_gen_runner: ^5.7.0
  flutter_gen: ^5.7.0
  file_picker: ^8.1.5
flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/js/highlight.min.js
  - assets/js/youtube_player.js
  - assets/categories.toml
  - assets/html_guide.md
  - assets/markdown_guide.md
  - assets/writing_prompts.toml
  - assets/css/bootstrap/bootstrap_darkly.min.css
  - assets/css/bootstrap/bootstrap_flatly.min.css
  - assets/css/bootstrap/bootstrap_litera.min.css
  - assets/css/bootstrap/bootstrap_neomorph.min.css
  - assets/css/bootstrap/bootstrap_sketchy.min.css
  - assets/css/bootstrap/bootstrap_slate.min.css
  - assets/css/highlight/1c-light.css
  - assets/css/highlight/a11y-dark.css
  - assets/css/highlight/a11y-light.css
  - assets/css/highlight/agate.css
  - assets/css/highlight/an-old-hope.css
  - assets/css/highlight/androidstudio.css
  - assets/css/highlight/arduino-light.css
  - assets/css/highlight/arta.css
  - assets/css/highlight/ascetic.css
  - assets/css/highlight/atom-one-dark-reasonable.css
  - assets/css/highlight/atom-one-dark.css
  - assets/css/highlight/atom-one-light.css
  - assets/css/highlight/brown-paper.css
  - assets/css/highlight/brown-papersq.png
  - assets/css/highlight/codepen-embed.css
  - assets/css/highlight/color-brewer.css
  - assets/css/highlight/cybertopia-cherry.css
  - assets/css/highlight/cybertopia-dimmer.css
  - assets/css/highlight/cybertopia-icecap.css
  - assets/css/highlight/cybertopia-saturated.css
  - assets/css/highlight/dark.css
  - assets/css/highlight/default.css
  - assets/css/highlight/devibeans.css
  - assets/css/highlight/docco.css
  - assets/css/highlight/far.css
  - assets/css/highlight/felipec.css
  - assets/css/highlight/foundation.css
  - assets/css/highlight/github-dark-dimmed.css
  - assets/css/highlight/github-dark.css
  - assets/css/highlight/github.css
  - assets/css/highlight/gml.css
  - assets/css/highlight/googlecode.css
  - assets/css/highlight/gradient-dark.css
  - assets/css/highlight/gradient-light.css
  - assets/css/highlight/grayscale.css
  - assets/css/highlight/hybrid.css
  - assets/css/highlight/idea.css
  - assets/css/highlight/intellij-light.css
  - assets/css/highlight/ir-black.css
  - assets/css/highlight/isbl-editor-dark.css
  - assets/css/highlight/isbl-editor-light.css
  - assets/css/highlight/kimbie-dark.css
  - assets/css/highlight/kimbie-light.css
  - assets/css/highlight/lightfair.css
  - assets/css/highlight/lioshi.css
  - assets/css/highlight/magula.css
  - assets/css/highlight/mono-blue.css
  - assets/css/highlight/monokai-sublime.css
  - assets/css/highlight/monokai.css
  - assets/css/highlight/night-owl.css
  - assets/css/highlight/nnfx-dark.css
  - assets/css/highlight/nnfx-light.css
  - assets/css/highlight/nord.css
  - assets/css/highlight/obsidian.css
  - assets/css/highlight/panda-syntax-dark.css
  - assets/css/highlight/panda-syntax-light.css
  - assets/css/highlight/paraiso-dark.css
  - assets/css/highlight/paraiso-light.css
  - assets/css/highlight/pojoaque.css
  - assets/css/highlight/pojoaque.jpg
  - assets/css/highlight/purebasic.css
  - assets/css/highlight/qtcreator-dark.css
  - assets/css/highlight/qtcreator-light.css
  - assets/css/highlight/rainbow.css
  - assets/css/highlight/rose-pine-dawn.css
  - assets/css/highlight/rose-pine-moon.css
  - assets/css/highlight/rose-pine.css
  - assets/css/highlight/routeros.css
  - assets/css/highlight/school-book.css
  - assets/css/highlight/shades-of-purple.css
  - assets/css/highlight/srcery.css
  - assets/css/highlight/stackoverflow-dark.css
  - assets/css/highlight/stackoverflow-light.css
  - assets/css/highlight/sunburst.css
  - assets/css/highlight/tokyo-night-dark.css
  - assets/css/highlight/tokyo-night-light.css
  - assets/css/highlight/tomorrow-night-blue.css
  - assets/css/highlight/tomorrow-night-bright.css
  - assets/css/highlight/vs.css
  - assets/css/highlight/vs2015.css
  - assets/css/highlight/xcode.css
  - assets/css/highlight/xt256.css
  - assets/css/highlight/base16/3024.css
  - assets/css/highlight/base16/apathy.css
  - assets/css/highlight/base16/apprentice.css
  - assets/css/highlight/base16/ashes.css
  - assets/css/highlight/base16/atelier-cave-light.css
  - assets/css/highlight/base16/atelier-cave.css
  - assets/css/highlight/base16/atelier-dune-light.css
  - assets/css/highlight/base16/atelier-dune.css
  - assets/css/highlight/base16/atelier-estuary-light.css
  - assets/css/highlight/base16/atelier-estuary.css
  - assets/css/highlight/base16/atelier-forest-light.css
  - assets/css/highlight/base16/atelier-forest.css
  - assets/css/highlight/base16/atelier-heath-light.css
  - assets/css/highlight/base16/atelier-heath.css
  - assets/css/highlight/base16/atelier-lakeside-light.css
  - assets/css/highlight/base16/atelier-lakeside.css
  - assets/css/highlight/base16/atelier-plateau-light.css
  - assets/css/highlight/base16/atelier-plateau.css
  - assets/css/highlight/base16/atelier-savanna-light.css
  - assets/css/highlight/base16/atelier-savanna.css
  - assets/css/highlight/base16/atelier-seaside-light.css
  - assets/css/highlight/base16/atelier-seaside.css
  - assets/css/highlight/base16/atelier-sulphurpool-light.css
  - assets/css/highlight/base16/atelier-sulphurpool.css
  - assets/css/highlight/base16/atlas.css
  - assets/css/highlight/base16/bespin.css
  - assets/css/highlight/base16/black-metal-bathory.css
  - assets/css/highlight/base16/black-metal-burzum.css
  - assets/css/highlight/base16/black-metal-dark-funeral.css
  - assets/css/highlight/base16/black-metal-gorgoroth.css
  - assets/css/highlight/base16/black-metal-immortal.css
  - assets/css/highlight/base16/black-metal-khold.css
  - assets/css/highlight/base16/black-metal-marduk.css
  - assets/css/highlight/base16/black-metal-mayhem.css
  - assets/css/highlight/base16/black-metal-nile.css
  - assets/css/highlight/base16/black-metal-venom.css
  - assets/css/highlight/base16/black-metal.css
  - assets/css/highlight/base16/brewer.css
  - assets/css/highlight/base16/bright.css
  - assets/css/highlight/base16/brogrammer.css
  - assets/css/highlight/base16/brush-trees-dark.css
  - assets/css/highlight/base16/brush-trees.css
  - assets/css/highlight/base16/chalk.css
  - assets/css/highlight/base16/circus.css
  - assets/css/highlight/base16/classic-dark.css
  - assets/css/highlight/base16/classic-light.css
  - assets/css/highlight/base16/codeschool.css
  - assets/css/highlight/base16/colors.css
  - assets/css/highlight/base16/cupcake.css
  - assets/css/highlight/base16/cupertino.css
  - assets/css/highlight/base16/danqing.css
  - assets/css/highlight/base16/darcula.css
  - assets/css/highlight/base16/dark-violet.css
  - assets/css/highlight/base16/darkmoss.css
  - assets/css/highlight/base16/darktooth.css
  - assets/css/highlight/base16/decaf.css
  - assets/css/highlight/base16/default-dark.css
  - assets/css/highlight/base16/default-light.css
  - assets/css/highlight/base16/dirtysea.css
  - assets/css/highlight/base16/dracula.css
  - assets/css/highlight/base16/edge-dark.css
  - assets/css/highlight/base16/edge-light.css
  - assets/css/highlight/base16/eighties.css
  - assets/css/highlight/base16/embers.css
  - assets/css/highlight/base16/equilibrium-dark.css
  - assets/css/highlight/base16/equilibrium-gray-dark.css
  - assets/css/highlight/base16/equilibrium-gray-light.css
  - assets/css/highlight/base16/equilibrium-light.css
  - assets/css/highlight/base16/espresso.css
  - assets/css/highlight/base16/eva-dim.css
  - assets/css/highlight/base16/eva.css
  - assets/css/highlight/base16/flat.css
  - assets/css/highlight/base16/framer.css
  - assets/css/highlight/base16/fruit-soda.css
  - assets/css/highlight/base16/gigavolt.css
  - assets/css/highlight/base16/github.css
  - assets/css/highlight/base16/google-dark.css
  - assets/css/highlight/base16/google-light.css
  - assets/css/highlight/base16/grayscale-dark.css
  - assets/css/highlight/base16/grayscale-light.css
  - assets/css/highlight/base16/green-screen.css
  - assets/css/highlight/base16/gruvbox-dark-hard.css
  - assets/css/highlight/base16/gruvbox-dark-medium.css
  - assets/css/highlight/base16/gruvbox-dark-pale.css
  - assets/css/highlight/base16/gruvbox-dark-soft.css
  - assets/css/highlight/base16/gruvbox-light-hard.css
  - assets/css/highlight/base16/gruvbox-light-medium.css
  - assets/css/highlight/base16/gruvbox-light-soft.css
  - assets/css/highlight/base16/hardcore.css
  - assets/css/highlight/base16/harmonic16-dark.css
  - assets/css/highlight/base16/harmonic16-light.css
  - assets/css/highlight/base16/heetch-dark.css
  - assets/css/highlight/base16/heetch-light.css
  - assets/css/highlight/base16/helios.css
  - assets/css/highlight/base16/hopscotch.css
  - assets/css/highlight/base16/horizon-dark.css
  - assets/css/highlight/base16/horizon-light.css
  - assets/css/highlight/base16/humanoid-dark.css
  - assets/css/highlight/base16/humanoid-light.css
  - assets/css/highlight/base16/ia-dark.css
  - assets/css/highlight/base16/ia-light.css
  - assets/css/highlight/base16/icy-dark.css
  - assets/css/highlight/base16/ir-black.css
  - assets/css/highlight/base16/isotope.css
  - assets/css/highlight/base16/kimber.css
  - assets/css/highlight/base16/london-tube.css
  - assets/css/highlight/base16/macintosh.css
  - assets/css/highlight/base16/marrakesh.css
  - assets/css/highlight/base16/materia.css
  - assets/css/highlight/base16/material-darker.css
  - assets/css/highlight/base16/material-lighter.css
  - assets/css/highlight/base16/material-palenight.css
  - assets/css/highlight/base16/material-vivid.css
  - assets/css/highlight/base16/material.css
  - assets/css/highlight/base16/mellow-purple.css
  - assets/css/highlight/base16/mexico-light.css
  - assets/css/highlight/base16/mocha.css
  - assets/css/highlight/base16/monokai.css
  - assets/css/highlight/base16/nebula.css
  - assets/css/highlight/base16/nord.css
  - assets/css/highlight/base16/nova.css
  - assets/css/highlight/base16/ocean.css
  - assets/css/highlight/base16/oceanicnext.css
  - assets/css/highlight/base16/one-light.css
  - assets/css/highlight/base16/onedark.css
  - assets/css/highlight/base16/outrun-dark.css
  - assets/css/highlight/base16/papercolor-dark.css
  - assets/css/highlight/base16/papercolor-light.css
  - assets/css/highlight/base16/paraiso.css
  - assets/css/highlight/base16/pasque.css
  - assets/css/highlight/base16/phd.css
  - assets/css/highlight/base16/pico.css
  - assets/css/highlight/base16/pop.css
  - assets/css/highlight/base16/porple.css
  - assets/css/highlight/base16/qualia.css
  - assets/css/highlight/base16/railscasts.css
  - assets/css/highlight/base16/rebecca.css
  - assets/css/highlight/base16/ros-pine-dawn.css
  - assets/css/highlight/base16/ros-pine-moon.css
  - assets/css/highlight/base16/ros-pine.css
  - assets/css/highlight/base16/sagelight.css
  - assets/css/highlight/base16/sandcastle.css
  - assets/css/highlight/base16/seti-ui.css
  - assets/css/highlight/base16/shapeshifter.css
  - assets/css/highlight/base16/silk-dark.css
  - assets/css/highlight/base16/silk-light.css
  - assets/css/highlight/base16/snazzy.css
  - assets/css/highlight/base16/solar-flare-light.css
  - assets/css/highlight/base16/solar-flare.css
  - assets/css/highlight/base16/solarized-dark.css
  - assets/css/highlight/base16/solarized-light.css
  - assets/css/highlight/base16/spacemacs.css
  - assets/css/highlight/base16/summercamp.css
  - assets/css/highlight/base16/summerfruit-dark.css
  - assets/css/highlight/base16/summerfruit-light.css
  - assets/css/highlight/base16/synth-midnight-terminal-dark.css
  - assets/css/highlight/base16/synth-midnight-terminal-light.css
  - assets/css/highlight/base16/tango.css
  - assets/css/highlight/base16/tender.css
  - assets/css/highlight/base16/tomorrow-night.css
  - assets/css/highlight/base16/tomorrow.css
  - assets/css/highlight/base16/twilight.css
  - assets/css/highlight/base16/unikitty-dark.css
  - assets/css/highlight/base16/unikitty-light.css
  - assets/css/highlight/base16/vulcan.css
  - assets/css/highlight/base16/windows-10-light.css
  - assets/css/highlight/base16/windows-10.css
  - assets/css/highlight/base16/windows-95-light.css
  - assets/css/highlight/base16/windows-95.css
  - assets/css/highlight/base16/windows-high-contrast-light.css
  - assets/css/highlight/base16/windows-high-contrast.css
  - assets/css/highlight/base16/windows-nt-light.css
  - assets/css/highlight/base16/windows-nt.css
  - assets/css/highlight/base16/woodland.css
  - assets/css/highlight/base16/xcode-dusk.css
  - assets/css/highlight/base16/zenburn.css
  - assets/images/flutter_logo.png
  - assets/images/2.0x/flutter_logo.png
  - assets/images/3.0x/flutter_logo.png
